mock_sgx = false
tx_sender = "star"
chain_id = "fairyring"
node_url = "http://127.0.0.1:26659"
ws_url = "ws://127.0.0.1:26659/websocket"
grpc_url = "http://127.0.0.1:26659"
# node_url = "https://neutron-testnet-rpc.polkachu.com"
# ws_url = "wss://neutron-testnet-rpc.polkachu.com/websocket"
# grpc_url = "https://grpc.baryon.remedy.tm.p2p.org:443"
enclave_rpc_addr = "https://127.0.0.1"
enclave_rpc_port = 11090
trusted_hash = ""
trusted_height = 0
release = true
